### ISSUE TITLE
Install error  of polsartools in PYTHON

### ISSUE THREAD

**Issue by sht9010** [Narayana-Rao/polsartools#4]
Dear Narayana-Rao,

Thank you very much for sharing this excellent polsartools.

we have a problem when installing this by python.

when we input "import polsartools as pst", it tells us:
"from polsartools.utils.utils import process_chunks_parallel,conv2d,eig22, time_it
ModuleNotFoundError: No module named 'polsartools.utils'"

Have you ever find this error?

Many thanks.

**Comment by Narayana-Rao** [comment]
Dear @sht9010! 

 I appreciate your feedback! I have pushed a new update with the fix. I’ve just pushed a new update to address this issue. Could you please try reinstalling the package and let me know if the problem persists? You may close this issue if this is solved.
Thanks!

**Comment by sht9010** [comment]
Dear Narayana Rao,

Thank you very much for your very quick response. 
Now I have successfully installed polsartools.

I am very interested in your developed tools for polsar data processing. It works very smoothly for SAR data users.
By the way, also thank you very much for your great contribution on SAR crop monitoring.
We have learned a lot.
Many thanks!

Dr.Hongtao

**Comment by sht9010** [comment]
> Dear @sht9010!
> 
> I appreciate your feedback! I have pushed a new update with the fix. I’ve just pushed a new update to address this issue. Could you please try reinstalling the package and let me know if the problem persists? You may close this issue if this is solved. Thanks!

Hi Dear Narayana Rao,

I was just find another problem when running the python code of polsartools.
It has error of "AttributeError: module 'polsartools' has no attribute 'polsar'" as bellow.

However,  I could find the module folder and their python files in the installed package.

![7616](https://github.com/user-attachments/assets/88f2ad6b-ea99-41f4-9bbc-a3c7b072bbf6)
![26124](https://github.com/user-attachments/assets/469b43ae-c83e-42ef-8001-e72ae9437cb0)
![27145](https://github.com/user-attachments/assets/facf3005-e664-4302-93be-349052ce09de)
![29471](https://github.com/user-attachments/assets/8ded3caa-d153-41c2-bbf9-ed125b8e489f)

Thank you very much if we could get your kind help.

Best regards,
Hongtao

**Comment by sht9010** [comment]
> Dear @sht9010!
> 
> I appreciate your feedback! I have pushed a new update with the fix. I’ve just pushed a new update to address this issue. Could you please try reinstalling the package and let me know if the problem persists? You may close this issue if this is solved. Thanks!

Dear Narayana Rao,

Thank you very much for your help and updates.

Although we have updated the installation of POLSARTOOS 0.4.1, we still get this error.

_**" File C:\ProgramData\Anaconda3\Lib\site-packages\polsartools\polsar\cp\cprvi.py:3
    from polsartools.utils.utils import process_chunks_parallel,conv2d,eig22, time_it
ModuleNotFoundError: No module named 'polsartools.utils'"**_

I will try to find some solutions.

we are grateful to have your further suggestions if possible.

Best.
Hongtao

**Comment by sht9010** [comment]
> Dear @sht9010!
> 
> I appreciate your feedback! I have pushed a new update with the fix. I’ve just pushed a new update to address this issue. Could you please try reinstalling the package and let me know if the problem persists? You may close this issue if this is solved. Thanks!

Hi Dear Narayana-Rao,

Fortunately, I recovered this problem by downloading the polsartools code zip file, and copy the "utils" folder into my installed package, i.e"...\ProgramData\anaconda3\Lib\site-packages\polsartools".

Before doing this, we can not find the "utils" file in "...\ProgramData\anaconda3\Lib\site-packages\polsartools" after the installation.  

By the way we also find some other problem:
In the installed file folder"C:\ProgramData\anaconda3\Lib\site-packages\polsartools\polsar" there is no "dcp" folder. In this case, when importing the polsartools, we may get errors could not find the "dcp" module, as  you set the "from . import cp,dcp,dxp,fp" in the file of "__init__.py" in the installed folder of ...:\ProgramData\anaconda3\Lib\site-packages\polsartools\polsar.
Hence, I rewrite it as ""from . import cp,dxp,fp" in the file of "__init__.py".

Hope this result could help our users and your team to refine this great tool .

Best regards.

Hongtao

**Comment by sht9010** [comment]
> > Dear @sht9010!
> > I appreciate your feedback! I have pushed a new update with the fix. I’ve just pushed a new update to address this issue. Could you please try reinstalling the package and let me know if the problem persists? You may close this issue if this is solved. Thanks!
> 
> Hi Dear Narayana-Rao,
> 
> Fortunately, I recovered this problem by downloading the polsartools code zip file, and copy the "utils" folder into my installed package, i.e"...\ProgramData\anaconda3\Lib\site-packages\polsartools".
> 
> Before doing this, we can not find the "utils" file in "...\ProgramData\anaconda3\Lib\site-packages\polsartools" after the installation.
> 
> By the way we also find some other problem: In the installed file folder"C:\ProgramData\anaconda3\Lib\site-packages\polsartools\polsar" there is no "dcp" folder. In this case, when importing the polsartools, we may get errors could not find the "dcp" module, as you set the "from . import cp,dcp,dxp,fp" in the file of "**init**.py" in the installed folder of ...:\ProgramData\anaconda3\Lib\site-packages\polsartools\polsar. Hence, I rewrite it as ""from . import cp,dxp,fp" in the file of "**init**.py".
> 
> Hope this result could help our users and your team to refine this great tool .
> 
> Best regards.
> 
> Hongtao

Also, we found that the polsartools works well for the rastersize smaller than 512*512. While process a bigger image it tells us:
"Error in processing chunk..." and "Chunk processing returned None",

In the code, does your team set an default image size that smaller than that of 512*512?

**Comment by Narayana-Rao** [comment]
Thank you Hongtao! (@sht9010),
These issues are because of our major structural update of the package to handle large datasets. The new version [0.4.2](https://pypi.org/project/polsartools/0.4.2/) should fix the above issues. 

`pip install polsartools==0.4.2`

Let me know if this solves the issue you are facing.

Thanks!

**Comment by sht9010** [comment]
> Thank you Hongtao! (@sht9010), These issues are because of our major structural update of the package to handle large datasets. The new version [0.4.2](https://pypi.org/project/polsartools/0.4.2/) should fix the above issues.
> 
> `pip install polsartools==0.4.2`
> 
> Let me know if this solves the issue you are facing.
> 
> Thanks!

Dear Narayana-Rao,

Thank you very much. 
Now, the version 0.4.2 works perfectly well.
I am appreciate for your response.

Best regards.
Hongtao
